server:
  port: 80
  servlet:
    context-path: /api
spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://${muy.database.host}:3306/bills?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${muy.database.username}
    password: ${muy.database.password}
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1 # 逻辑已删除字段
      logic-not-delete-value: 0 # 逻辑未删除字段
logging:
  level:
    com.qingmuy: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.qingmuy.controller
knife4j:
  enable: true
jjwt:
  # jjwt密钥
  secret: chaojizhenzhu#@114514
  # token过期时间
  ttl: 7200000
  # 令牌名称
  token-name: token